import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import LenisWrapper from "@/components/layouts/LenisWrapper";
import Providers from "./_providers/Providers";
import { Toaster } from "@/components/ui/sonner";
import React from "react";
import { cn } from "@/lib/utils";
import { getSession } from "@/lib/auth";

export const metadata: Metadata = {
	title: "RCollabs",
	description: "Generated by create next app",
	icons: {
		icon: "/assets/favicon.ico",
	},
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<head>
				<script
					crossOrigin="anonymous"
					src="//unpkg.com/react-scan/dist/auto.global.js"
				/>
			</head>
			<body className={cn(GeistSans.className)}>
				<ThemeProvider
				// attribute="class"
				// defaultTheme="system"
				// enableSystem
				// disableTransitionOnChange
				>
					<Toaster richColors position="top-center" />
					<Providers data={session?.user}>
						<LenisWrapper>{children}</LenisWrapper>
					</Providers>
				</ThemeProvider>
			</body>
		</html>
	);
}
