const config = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  SERVER_API_VERSION: process.env.NEXT_PUBLIC_SERVER_API_VERSION,
  SERVER_API_TYPE: process.env.NEXT_PUBLIC_SERVER_API_TYPE,
  SERVER_API_URL: `${process.env.NEXT_PUBLIC_BASE_URL}/api/${process.env.NEXT_PUBLIC_SERVER_API_VERSION}/${process.env.NEXT_PUBLIC_SERVER_API_TYPE}`,

  // socials
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
};

export default config;
