const config = {
	BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
	SERVER_API_VERSION: process.env.NEXT_PUBLIC_SERVER_API_VERSION,
	SERVER_API_TYPE: process.env.NEXT_PUBLIC_SERVER_API_TYPE,
	SERVER_API_URL: `${process.env.NEXT_PUBLIC_BASE_URL}/api/${process.env.NEXT_PUBLIC_SERVER_API_VERSION}/${process.env.NEXT_PUBLIC_SERVER_API_TYPE}`,

	// socials
	GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
	GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
	GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

	// storage
	UPLOADTHING_PUBLIC_KEY: process.env.UPLOADTHING_PUBLIC_KEY,
	UPLOADTHING_API_KEY: process.env.NEXT_PUBLIC_UPLOADTHING_API_KEY,
	UPLOADTHING_API_URL: process.env.NEXT_PUBLIC_UPLOADTHING_API_URL,

	// vector
	PINECONE_API_KEY: process.env.PINECONE_AI_SEARCH_API_KEY,
	PINECONE_INDEX_NAME: process.env.PINECONE_INDEX_NAME,
	PINECONE_INDEX_CONFIG: process.env.PINECONE_INDEX_CONFIG,
	PINECONE_NAMESPACE: process.env.PINECONE_NAMESPACE,

	// score system
	SCORE_CUTOFF: 0.78,

	// extension
	EXTENSION_ORIGIN: process.env.EXTENSION_ORIGIN,

	IP_INFO_TOKEN: process.env.NEXT_PUBLIC_IP_INFO_TOKEN,
};

export default config;
